### ISSUE TITLE
GameManager

### ISSUE THREAD

**Issue by gdavid** [Christophe-Dupin/labyrinth#2]
https://github.com/Christophe-Dupin/labyrinth/blob/099fd227bf8f66ad67cb8c57d482990a94bbb228/gameManager/gamemanager.py#L43

Tu peux merge cette fonction avec get_item. Cette décomposition ne sert à rien; pire, elle est contre performante vu que tu reboucle sur les items avec un if.

https://github.com/Christophe-Dupin/labyrinth/blob/099fd227bf8f66ad67cb8c57d482990a94bbb228/gameManager/gamemanager.py#L57

number_item a plus sa place dans model.
Tu pourrais également choisir d'avoir une vraie classe library, qui aurait une fonction add qui permettrait le stockage de l'objet et la mise à jour de sa position. Dans la fonction Victory il te suffirait alors de comparer le nombre d'objets dans les listes library et lstitem.
Ou tu pourrais faire ça dans Hero (puisque c'est lui qui cumule des objets).

Plus généralement GameManager me parait pouvoir être merged dans controler.

**Comment by Christophe-Dupin** [comment]
Merci Guillaume pour tes retours je vais regarder ça demain .
Biz

**Comment by Christophe-Dupin** [comment]
https://github.com/Christophe-Dupin/labyrinth/tree/hotfix/guillaume_feedback

j'ai fais tes modifs sur cette branche dis moi ce que tu en penses 
Merci d'avance
